---
# handlers file for docker_host

- name: enable docker
  service:
    name: docker
    enabled: true
  become: true

- name: start docker
  service:
    name: docker
    state: started
  become: true

- name: restart docker
  service:
    name: docker
    state: restarted
  become: true
