---

- name: Clone search engine microservices git repository
  git:
    dest: "{{ search_engine_work_dir }}"
    repo: "{{ search_engine_repo }}"
    version: "{{ search_engine_repo_version }}"

- name: Copy docker compose environment file
  copy:
    src: "{{ search_engine_docker_compose_env }}"
    dest: "{{ search_engine_work_dir }}/docker/.env"
    mode: 0640
  no_log: true

- name: Copy alertmanager secrets file
  copy:
    src: "{{ search_engine_alertmanager_secrets }}"
    dest: "{{ search_engine_work_dir }}/monitoring/alertmanager/alertmanager.secrets"
    mode: 0640
  no_log: true
