---
galaxy_info:
  author: Aleksandr Loktionov
  description: docker host configuration role
  company: none
  license: BSD
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - system
dependencies: []
