---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      labels:
        app: search_engine
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: ui
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: ui
          protocol: TCP
        env:
        - name: MONGO
          value: {{ .Values.mongodbHost | default (printf "%s-mongodb" .Release.Name) }}
