---
global:
  hosts:
    domain: loktionovam.com

certmanager-issuer:
  email: devops@loktionovam.com

gitlab:
  migrations:
    image:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-rails-ce
  sidekiq:
    image:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ce
  unicorn:
    image:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-unicorn-ce
    workhorse:
      image: registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ce
  task-runner:
    image:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-task-runner-ce
