version: '3.3'
services:
  prometheus-server:
    image: ${USER_NAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - front_net
      - back_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v${NODE_EXPORTER_VERSION}
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
  mongodb_exporter:
    image: loktionovam/mongodb_exporter:${MONGODB_EXPORTER_VERSION}
    environment:
      - MONGODB_URL=mongodb://crawler_db:27017
    networks:
      - front_net
      - back_net
  cadvisor:
    image: google/cadvisor:v${CADVISOR_VERSION}
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - front_net
  grafana:
    image: loktionovam/grafana:${GRAFANA_VERSION}
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus-server
    ports:
      - 3000:3000
    networks:
      - front_net
  alertmanager:
    image: ${USER_NAME}/alertmanager:${ALERTMANGER_VERSION}
    ports:
      - 9093:9093
    networks:
      - front_net
volumes:
  prometheus_data:
  grafana_data:
networks:
  back_net:
  front_net:
