version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd:${FLUENTD_VERSION}
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:${KIBANA_VERSION}
    ports:
      - "5601:5601"

networks:
  back_net:
  front_net:
