{
 "title": "Crawler service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Site connection time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Crawler page parse time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Rate of page parse",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Pages" }
   ],
   "targets": [
    { "expr": "rate(crawler_pages_parsed[1m])" }
   ]
  }
 ]
}