{
 "title": "RabbitMQ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Default VHost stat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "Connections" },
    { "expr": "rabbitmq_channels", "legendFormat": "Channels" },
    { "expr": "rabbitmq_consumers", "legendFormat": "Consumers" },
    { "expr": "rabbitmq_exchanges", "legendFormat": "Exchanges" },
    { "expr": "rabbitmq_queues", "legendFormat": "Queues" }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages_published_total[5m])",
     "legendFormat": "Messages published"
    },
    {
     "expr": "sum(irate(rabbitmq_queue_messages_delivered_total[5m]))",
     "legendFormat": "Messages delivered"
    }
   ]
  },
  {
   "title": "Erlang VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "Erlang VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs[5m])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_words_reclaimed[5m])",
     "legendFormat": "Words Reclaimed"
    }
   ]
  },
  {
   "title": "Erlang VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total[5m])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total[5m])",
     "legendFormat": "Received Bytes"
    }
   ]
  }
 ]
}