---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: search-engine-xenial
    box: ubuntu/xenialh64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 8000, host: 8000"
      - "vm.network 'forwarded_port', guest: 3000, host: 3000"
      - "vm.network 'forwarded_port', guest: 9090, host: 9090"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        search_engine_repo_version: feature/docker_gcp
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
